### ISSUE TITLE
Open button results in a timeout on Android 12

### ISSUE THREAD

**Issue by ComputerOnFire** [treehouses/flutter-ble-terminal#50]
Connections can be established, but opening results in a timeout.

```
I/flutter (15930): FOUND DEVICES
D/FlutterBluePlugin(15930): mDevices size: 1
D/BluetoothGatt(15930): discoverServices() - device: B8:27:EB:0D:27:02
D/BluetoothGatt(15930): cancelOpen() - device: B8:27:EB:0D:27:02
E/flutter (15930): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: TimeoutException after 0:00:20.000000: Failed to connect in time.
E/flutter (15930): #0      BluetoothDevice.connect.<anonymous closure> (package:flutter_blue/src/bluetooth_device.dart:33:9)
E/flutter (15930): #1      _rootRun (dart:async/zone.dart:1420:47)
E/flutter (15930): #2      _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (15930): #3      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (15930): #4      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter (15930): #5      _rootRun (dart:async/zone.dart:1428:13)
E/flutter (15930): #6      _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (15930): #7      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1260:23)
E/flutter (15930): #8      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (15930): #9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
E/flutter (15930): #10     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
E/flutter (15930): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter (15930):
D/BluetoothGatt(15930): onClientConnectionState() - status=0 clientIf=10 device=B8:27:EB:0D:27:02
D/FlutterBluePlugin(15930): [onConnectionStateChange] status: 0 newState: 0
D/BluetoothGatt(15930): close()
D/BluetoothGatt(15930): unregisterApp() - mClientIf=10
I/flutter (15930): Scan result 51
```

**Comment by ComputerOnFire** [comment]
Solution: Use RPI4 with built-in bluetooth, this seemed to only happen with RPI3 and a USB bluetooth adapter
